import Head from 'next/head'

export async function getStaticProps() {
  return { props: {
    products: [
      { id: 'p1', title: 'Product 1' }
    ]
  } };
}

interface HomeProps {
  products: {
    id: string
    title: string
  }[]
}

export default function Home({ products } : HomeProps) {
  console.log(products);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Project</h1>
        <ul>
          {products.map(p => (
            <li key={p.id}>{p.title}</li>
          ))}
        </ul>
      </main>
    </>
  )
}
